# All SpaceVim option below [option] section
[options]
# bootstrap_before = "myspacevim#before"
# bootstrap_after = "myspacevim#after"

# set spacevim theme. by default colorscheme layer is not loaded,
# if you want to use more colorscheme, please load the colorscheme
# layer
# Detect colorscheme used by dynamic-colors and fallback to NeoSolarized
colorscheme = "SpaceVim"
# colorscheme_default = "NeoSolarized"
background = "dark"
# Disable guicolors in basic mode, many terminal do not support 24bit
# true colors
enable_guicolors = true

guifont = "SauceCodePro NF:h13"
# guifont = "DejaVuSansMono_Nerd_Font:h14:cANSI:qDRAFT"

# Disable statusline separator, if you want to use other value, please
# install nerd fonts
statusline_separator = "arrow"
statusline_inactive_separator = "arrow"
enable_tabline_filetype_icon = true
enable_statusline_display_mode = false

# 0: 1 ➛ ➊ 1: 1 ➛ ➀ 2: 1 ➛ ⓵ 3: 1 ➛ ¹ 4: 1 ➛ 1
buffer_index_type = 4

# 0: 1 ➛ ➊ 1: 1 ➛ ➀ 2: 1 ➛ ⓵ 3: 1 ➛ 1
windows_index_type = 3

statusline_unicode_symbols = 1

# If there is a particular plugin you don't like, you can define this
# variable to disable them entirely:
disabled_plugins=['vim-gutentags']

default_indent = 4
# 恢复q的正常用途。<Leader>qr是宏录制的快捷键
#windows_smartclose = ''

# Wildignore
wildignore = """\
              */tmp/*,*.so,*.swp,*.zip,*.class,tags,\
              *.jpg,*.ttf,*.TTF,*.png,*/target/*,\
              .git,.svn,.hg,.DS_Store,*.svg,.*/,\
              bin*/**/gcc-*/**,*.gcov,*.o"""

realtime_leader_guide = 1
enable_vimfiler_welcome = 1

enable_tabline_filetype_icon = 1
enable_statusline_display_mode = 0
enable_os_fileformat_icon = 1

# Disable delimitmate
autocomplete_parens = 0

snippet_engine = 'ultisnips'

src_root = '~/workspace/'

# 0: disable autochdir
# 1: change to project root automatically
# 2: change to directory of current file automatically
project_rooter_automatically = 2

# default layers
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "nil"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'leaderf'

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

# [[layers]]
# name = 'sudo'

# additional layers
[[layers]]
name = 'VersionControl'

[[layers]]
name = 'colorscheme'

[[layers]]
name = 'denite'

[[layers]]
name = 'incsearch'
enable = false

[[layers]]
name = 'tools'

[[layers]]
name = 'unite'

# begin optional layers
[[layers]]
name = 'lang#asciidoc'
enable = true

[[layers]]
name = 'lang#javascript'
enable = true

[[layers]]
name = 'lang#markdown'
enable = true

[[layers]]
name = 'lang#toml'
enable = true

[[layers]]
name = 'lang#vim'
enable = true

[[layers]]
name = 'lang#xml'
enable = true

[[layers]]
name = 'tags'
enable = true


# end optional layers

[[custom_plugins]]
# 彩色显示#RRGGBB
name = 'lilydjwg/colorizer'
merged = 0

[[custom_plugins]]
name ='thawk/vim-asciidoc-folding'
lazy = 1
on_ft = 'asciidoc'

[[custom_plugins]]
name ='masukomi/vim-markdown-folding'
lazy = 1
on_ft = 'markdown'

[[custom_plugins]]
name ='thawk/vim-b2'
lazy = 0

[[custom_plugins]]
name = 'ConradIrwin/vim-bracketed-paste'

[[custom_plugins]]
name = 'derekwyatt/vim-fswitch'
lazy = 1
on_func = ['FSwitch']
on_cmd = ['FSHere','FSRight','FSSplitRight','FSLeft','FSSplitLeft','FSAbove','FSSplitAbove','FSBelow','FSSplitBelow']


[[custom_plugins]]
name = 'haya14busa/dein-command.vim'
lazy = 1
on_cmd = ['Dein']

[[custom_plugins]]
name = 'vernonrj/Mark--Karkat'
lazy = 1
on_cmd = ['Mark', 'MarkClear', 'Marks', 'MarkLoad', 'MarkSave', 'MarkPalette']
on_map = ['<Plug>Mark']

[[custom_plugins]]
name = 'sickill/vim-monokai'


